baseURL = "https://samana.netlify.com/"
languageCode = "fr-be"
title = "Samana le souffle, yoga et méditation"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
    description = "Chloé Dujardin donne des cours de yoga et de méditation pleine conscience à Liège. Pratique authentique basée sur le souffle qui lie le corps et l’esprit."