baseURL = "https://samana.netlify.com/"
languageCode = "fr-be"
title = "Samana le souffle, yoga et méditation"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    description = "Description de Samana"
